// Generated by LiveScript 1.5.0
(function(){
  var React, createTag, create, install, html, svg, toString$ = {}.toString;
  React = require('react');
  createTag = function(dom){
    return function(input){
      if (['Object', 'Undefined', 'Null'].indexOf(toString$.call(input).slice(8, -1))) {
        return function(){
          return React.DOM[name].apply(this, [input != null ? input : null].concat(Array.prototype.slice.call(arguments)));
        };
      }
      return dom.apply(this, [null].concat(Array.prototype.slice.call(arguments)));
    };
  };
  create = function(component){
    if (typeof component === 'object') {
      component = React.createClass(component);
    }
    return createTag(React.createFactory(component));
  };
  exports.React = React;
  exports.Component = React.Component;
  exports.create = create;
  exports.type = function(){
    var types, props;
    types = {};
    props = ['array', 'bool', 'func', 'number', 'object', 'string', 'node', 'element', 'instanceOf', 'oneOf', 'oneOfType', 'arrayOf', 'objectOf', 'shape'].map(function(prop){
      return types[prop] = React.PropTypes[prop];
    });
    return types;
  }();
  install = function(name){
    return exports[name] = createTag(React.DOM[name]);
  };
  html = ['a', 'abbr', 'address', 'area', 'article', 'aside', 'audio', 'b', 'base', 'bdi', 'bdo', 'big', 'blockquote', 'body', 'br', 'button', 'canvas', 'caption', 'cite', 'code', 'col', 'colgroup', 'data', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'hr', 'html', 'i', 'iframe', 'img', 'input', 'ins', 'kbd', 'keygen', 'label', 'legend', 'li', 'link', 'main', 'map', 'mark', 'menu', 'menuitem', 'meta', 'meter', 'nav', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'param', 'picture', 'pre', 'progress', 'q', 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'section', 'select', 'small', 'source', 'span', 'strong', 'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track', 'u', 'ul', 'var$', 'video', 'wbr'].map(install);
  svg = ['circle', 'clipPath', 'defs', 'ellipse', 'g', 'image', 'line', 'linearGradient', 'mask', 'path', 'pattern', 'polygon', 'polyline', 'radialGradient', 'rect', 'stop', 'svg', 'text', 'tspan'].map(install);
}).call(this);
